### PR TITLE
Adding custom css so code size is 90%

### PR DESCRIPTION
**Pull request by djw8605**

### CODE REVIEW

**Comment by djw8605** [comment]
@bbockelm Do you like the code as 90%.  I think it looks a lot better (though, I'm not sure how to show it to you, if this was a fork, I could point you to my copy, but it's mine 😄  )

**Comment by bbockelm** [comment]
Screenshot?

Anyhow, the much-more-annoying css issue is `<pre><code>` formatting within lists is all screwy.

Look at the code in _Enabling HTCondor-CE_ here: http://djw8605.github.io/osg-docs/Computing_Element/HTCondor_CE/#configuring-htcondor-ce

**Comment by djw8605** [comment]
I don't see any pre's around that code.  I just see `<code>`

**Comment by djw8605** [comment]
Closing for moving.

**Pull request closed without merging**
